---
configure_terminal: false
configure_osx: true
configure_dotfiles: true

configure_dock: true
dockitems_remove: [
  - Launchpad
  - Safari
  - Mail
  - Maps
  - Photos
  - Calendar
  - Contacts
  - Reminders
  - Notes
  - TV
  - Music
  - Podcasts
  - News
  - 'App Store'
]
dockitems_persist: [
  - name: 'Microsoft Edge'
    path: '/Applications/Microsoft Edge.app'
    pos: 2
  - name: '1Password'
    path: '/Applications/1Password.app'
    pos: 3
  - name: 'iTerm'
    path: '/Applications/iTerm.app'
    pos: 4
  - name: 'GoLand'
    path: '/Applications/GoLand.app'
    pos: 5
  - name: 'Discord'
    path: '/Applications/Discord.app'
    pos: 6
]

dotfiles_repo: https://github.com/nqui/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/env-config/dotfiles
dotfiles_files:
  - .zshrc
  - .gitignore
  - .osx
  - .vimrc
  - .config/pip/pip.conf
  - .nanorc
  - .gitconfig
  - .config/iterm2/iterm-profiles.json
  - "Library/Application Support/Rectangle/RectangleConfig.json"

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - git
  - httpie
  - iperf
  - ssh-copy-id
  - openssl
  - wget
  - zsh-history-substring-search
  - zsh-autosuggestions
  - asdf
  - nano
  - nanorc
  - zsh
  - powerlevel10k
  - go
  - tree

homebrew_cask_apps:
  - docker
  - slack
  - onedrive
  - 1password
  - iterm2
  - discord
  - goland
  - pycharm
  - adguard
  - microsoft-edge
  - rectangle
  - flux
